# Generated by Django 4.1 on 2022-08-28 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="cared_by",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="id",
        ),
        migrations.AddField(
            model_name="animal",
            name="cared_for_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
